module.exports.stocksJson = {
    "AAPL": {
      "quote": {
        "symbol": "AAPL",
        "companyName": "Apple Inc",
        "primaryExchange": "NASDAQ/NGS (GLOBAL SELECT MARKET)",
        "calculationPrice": "close",
        "open": null,
        "openTime": null,
        "openSource": "official",
        "close": null,
        "closeTime": null,
        "closeSource": "official",
        "high": null,
        "highTime": 1613163582052,
        "highSource": "IEX Last Trade",
        "low": null,
        "lowTime": null,
        "lowSource": null,
        "latestPrice": 135.37,
        "latestSource": "Close",
        "latestTime": "February 12, 2021",
        "latestUpdate": 1613166728452,
        "latestVolume": null,
        "iexRealtimePrice": null,
        "iexRealtimeSize": null,
        "iexLastUpdated": null,
        "delayedPrice": null,
        "delayedPriceTime": null,
        "oddLotDelayedPrice": null,
        "oddLotDelayedPriceTime": null,
        "extendedPrice": null,
        "extendedChange": null,
        "extendedChangePercent": null,
        "extendedPriceTime": null,
        "previousClose": 135.13,
        "previousVolume": 64280029,
        "change": 0.24,
        "changePercent": 0.00178,
        "volume": null,
        "iexMarketPercent": null,
        "iexVolume": null,
        "avgTotalVolume": 101679098,
        "iexBidPrice": null,
        "iexBidSize": null,
        "iexAskPrice": null,
        "iexAskSize": null,
        "iexOpen": 135.41,
        "iexOpenTime": 1613164557553,
        "iexClose": 135.42,
        "iexCloseTime": 1613163597511,
        "marketCap": 2272604555520,
        "peRatio": 36.79,
        "week52High": 144.87,
        "week52Low": 52.74,
        "ytdChange": 0.02350206623796158,
        "lastTradeTime": 1613163597511,
        "isUSMarketOpen": false
      }
    },
    "FB": {
      "quote": {
        "symbol": "FB",
        "companyName": "Facebook Inc - Class A",
        "primaryExchange": "NASDAQ/NGS (GLOBAL SELECT MARKET)",
        "calculationPrice": "close",
        "open": null,
        "openTime": null,
        "openSource": "official",
        "close": null,
        "closeTime": null,
        "closeSource": "official",
        "high": null,
        "highTime": null,
        "highSource": null,
        "low": null,
        "lowTime": null,
        "lowSource": null,
        "latestPrice": 270.5,
        "latestSource": "Close",
        "latestTime": "February 12, 2021",
        "latestUpdate": 1613163601230,
        "latestVolume": null,
        "iexRealtimePrice": null,
        "iexRealtimeSize": null,
        "iexLastUpdated": null,
        "delayedPrice": null,
        "delayedPriceTime": null,
        "oddLotDelayedPrice": null,
        "oddLotDelayedPriceTime": null,
        "extendedPrice": null,
        "extendedChange": null,
        "extendedChangePercent": null,
        "extendedPriceTime": null,
        "previousClose": 270.39,
        "previousVolume": 12828572,
        "change": 0.11,
        "changePercent": 0.00041,
        "volume": null,
        "iexMarketPercent": null,
        "iexVolume": null,
        "avgTotalVolume": 20312157,
        "iexBidPrice": null,
        "iexBidSize": null,
        "iexAskPrice": null,
        "iexAskSize": null,
        "iexOpen": 270.69,
        "iexOpenTime": 1613163594615,
        "iexClose": 270.69,
        "iexCloseTime": 1613163594615,
        "marketCap": 772007034624,
        "peRatio": 26.81,
        "week52High": 304.67,
        "week52Low": 137.1,
        "ytdChange": -0.009327882559672117,
        "lastTradeTime": 1613163598535,
        "isUSMarketOpen": false
      }
    },
    "TSLA": {
      "quote": {
        "symbol": "TSLA",
        "companyName": "Tesla Inc",
        "primaryExchange": "NASDAQ/NGS (GLOBAL SELECT MARKET)",
        "calculationPrice": "close",
        "open": null,
        "openTime": null,
        "openSource": "official",
        "close": null,
        "closeTime": null,
        "closeSource": "official",
        "high": null,
        "highTime": null,
        "highSource": null,
        "low": null,
        "lowTime": null,
        "lowSource": null,
        "latestPrice": 816.12,
        "latestSource": "Close",
        "latestTime": "February 12, 2021",
        "latestUpdate": 1613166216793,
        "latestVolume": null,
        "iexRealtimePrice": null,
        "iexRealtimeSize": null,
        "iexLastUpdated": null,
        "delayedPrice": null,
        "delayedPriceTime": null,
        "oddLotDelayedPrice": null,
        "oddLotDelayedPriceTime": null,
        "extendedPrice": null,
        "extendedChange": null,
        "extendedChangePercent": null,
        "extendedPriceTime": null,
        "previousClose": 811.66,
        "previousVolume": 21622753,
        "change": 4.46,
        "changePercent": 0.00549,
        "volume": null,
        "iexMarketPercent": null,
        "iexVolume": null,
        "avgTotalVolume": 24425904,
        "iexBidPrice": null,
        "iexBidSize": null,
        "iexAskPrice": null,
        "iexAskSize": null,
        "iexOpen": 816.6,
        "iexOpenTime": 1613163597760,
        "iexClose": 816.6,
        "iexCloseTime": 1613163597760,
        "marketCap": 783355641684,
        "peRatio": 1280.99,
        "week52High": 900.4,
        "week52Low": 70.1,
        "ytdChange": 0.16200791914067492,
        "lastTradeTime": 1613163598413,
        "isUSMarketOpen": false
      }
    },
    "TWTR": {
      "quote": {
        "symbol": "TWTR",
        "companyName": "Twitter Inc",
        "primaryExchange": "NEW YORK STOCK EXCHANGE, INC.",
        "calculationPrice": "close",
        "open": null,
        "openTime": null,
        "openSource": "official",
        "close": null,
        "closeTime": null,
        "closeSource": "official",
        "high": null,
        "highTime": 1613163598405,
        "highSource": "15 minute delayed price",
        "low": null,
        "lowTime": 1613140332823,
        "lowSource": "15 minute delayed price",
        "latestPrice": 71.9,
        "latestSource": "Close",
        "latestTime": "February 12, 2021",
        "latestUpdate": 1613174400004,
        "latestVolume": null,
        "iexRealtimePrice": null,
        "iexRealtimeSize": null,
        "iexLastUpdated": null,
        "delayedPrice": null,
        "delayedPriceTime": null,
        "oddLotDelayedPrice": null,
        "oddLotDelayedPriceTime": null,
        "extendedPrice": null,
        "extendedChange": null,
        "extendedChangePercent": null,
        "extendedPriceTime": null,
        "previousClose": 68.56,
        "previousVolume": 30470036,
        "change": 3.34,
        "changePercent": 0.04872,
        "volume": null,
        "iexMarketPercent": null,
        "iexVolume": null,
        "avgTotalVolume": 23372175,
        "iexBidPrice": null,
        "iexBidSize": null,
        "iexAskPrice": null,
        "iexAskSize": null,
        "iexOpen": 71.94,
        "iexOpenTime": 1613163596891,
        "iexClose": 71.94,
        "iexCloseTime": 1613163596891,
        "marketCap": 57185635593,
        "peRatio": -45.8,
        "week52High": 73.18,
        "week52Low": 20,
        "ytdChange": 0.37651316712834737,
        "lastTradeTime": 1613163598402,
        "isUSMarketOpen": false
      }
    },
    "BAC": {
      "quote": {
        "symbol": "BAC",
        "companyName": "Bank Of America Corp.",
        "primaryExchange": "NEW YORK STOCK EXCHANGE, INC.",
        "calculationPrice": "close",
        "open": null,
        "openTime": null,
        "openSource": "official",
        "close": null,
        "closeTime": null,
        "closeSource": "official",
        "high": null,
        "highTime": 1613163598026,
        "highSource": "15 minute delayed price",
        "low": null,
        "lowTime": 1613140203022,
        "lowSource": "15 minute delayed price",
        "latestPrice": 33.37,
        "latestSource": "Close",
        "latestTime": "February 12, 2021",
        "latestUpdate": 1613174400003,
        "latestVolume": null,
        "iexRealtimePrice": null,
        "iexRealtimeSize": null,
        "iexLastUpdated": null,
        "delayedPrice": null,
        "delayedPriceTime": null,
        "oddLotDelayedPrice": null,
        "oddLotDelayedPriceTime": null,
        "extendedPrice": null,
        "extendedChange": null,
        "extendedChangePercent": null,
        "extendedPriceTime": null,
        "previousClose": 32.88,
        "previousVolume": 29479877,
        "change": 0.49,
        "changePercent": 0.0149,
        "volume": null,
        "iexMarketPercent": null,
        "iexVolume": null,
        "avgTotalVolume": 48530754,
        "iexBidPrice": null,
        "iexBidSize": null,
        "iexAskPrice": null,
        "iexAskSize": null,
        "iexOpen": 33.365,
        "iexOpenTime": 1613163596456,
        "iexClose": 33.365,
        "iexCloseTime": 1613163596456,
        "marketCap": 288676852089,
        "peRatio": 16.44,
        "week52High": 34.37,
        "week52Low": 17.59,
        "ytdChange": 0.11585677994061369,
        "lastTradeTime": 1613163597964,
        "isUSMarketOpen": false
      }
    },
    "VS": {
      "quote": {
        "symbol": "VS",
        "companyName": "Versus Systems Inc",
        "primaryExchange": "NASDAQ CAPITAL MARKET",
        "calculationPrice": "close",
        "open": null,
        "openTime": null,
        "openSource": "official",
        "close": null,
        "closeTime": null,
        "closeSource": "official",
        "high": null,
        "highTime": null,
        "highSource": null,
        "low": null,
        "lowTime": null,
        "lowSource": null,
        "latestPrice": 10.4,
        "latestSource": "Close",
        "latestTime": "February 12, 2021",
        "latestUpdate": 1613170001709,
        "latestVolume": null,
        "iexRealtimePrice": null,
        "iexRealtimeSize": null,
        "iexLastUpdated": null,
        "delayedPrice": null,
        "delayedPriceTime": null,
        "oddLotDelayedPrice": null,
        "oddLotDelayedPriceTime": null,
        "extendedPrice": null,
        "extendedChange": null,
        "extendedChangePercent": null,
        "extendedPriceTime": null,
        "previousClose": 9.48,
        "previousVolume": 20865,
        "change": 0.92,
        "changePercent": 0.09705,
        "volume": null,
        "iexMarketPercent": null,
        "iexVolume": null,
        "avgTotalVolume": 54147,
        "iexBidPrice": null,
        "iexBidSize": null,
        "iexAskPrice": null,
        "iexAskSize": null,
        "iexOpen": 10.525,
        "iexOpenTime": 1613163242771,
        "iexClose": 10.525,
        "iexCloseTime": 1613163242771,
        "marketCap": 110480011,
        "peRatio": null,
        "week52High": 10.72,
        "week52Low": 6.75,
        "ytdChange": 159.09705,
        "lastTradeTime": 1613163537863,
        "isUSMarketOpen": false
      }
    },
    "MA": {
      "quote": {
        "symbol": "MA",
        "companyName": "Mastercard Incorporated - Class A",
        "primaryExchange": "NEW YORK STOCK EXCHANGE, INC.",
        "calculationPrice": "close",
        "open": null,
        "openTime": null,
        "openSource": "official",
        "close": null,
        "closeTime": null,
        "closeSource": "official",
        "high": null,
        "highTime": 1613163598440,
        "highSource": "15 minute delayed price",
        "low": null,
        "lowTime": 1613143162929,
        "lowSource": "IEX real time price",
        "latestPrice": 341,
        "latestSource": "Close",
        "latestTime": "February 12, 2021",
        "latestUpdate": 1613174400003,
        "latestVolume": null,
        "iexRealtimePrice": null,
        "iexRealtimeSize": null,
        "iexLastUpdated": null,
        "delayedPrice": null,
        "delayedPriceTime": null,
        "oddLotDelayedPrice": null,
        "oddLotDelayedPriceTime": null,
        "extendedPrice": null,
        "extendedChange": null,
        "extendedChangePercent": null,
        "extendedPriceTime": null,
        "previousClose": 342.87,
        "previousVolume": 5110767,
        "change": -1.87,
        "changePercent": -0.00545,
        "volume": null,
        "iexMarketPercent": null,
        "iexVolume": null,
        "avgTotalVolume": 4682539,
        "iexBidPrice": null,
        "iexBidSize": null,
        "iexAskPrice": null,
        "iexAskSize": null,
        "iexOpen": 340.86,
        "iexOpenTime": 1613163595729,
        "iexClose": 340.86,
        "iexCloseTime": 1613163595729,
        "marketCap": 335935097674,
        "peRatio": 51.12,
        "week52High": 366.36,
        "week52Low": 198.93,
        "ytdChange": -0.048896331027599424,
        "lastTradeTime": 1613163598423,
        "isUSMarketOpen": false
      }
    },
    "TGT": {
      "quote": {
        "symbol": "TGT",
        "companyName": "Target Corp",
        "primaryExchange": "NEW YORK STOCK EXCHANGE, INC.",
        "calculationPrice": "close",
        "open": null,
        "openTime": null,
        "openSource": "official",
        "close": null,
        "closeTime": null,
        "closeSource": "official",
        "high": null,
        "highTime": 1613163598250,
        "highSource": "15 minute delayed price",
        "low": null,
        "lowTime": 1613155541723,
        "lowSource": "15 minute delayed price",
        "latestPrice": 191.43,
        "latestSource": "Close",
        "latestTime": "February 12, 2021",
        "latestUpdate": 1613174400001,
        "latestVolume": null,
        "iexRealtimePrice": null,
        "iexRealtimeSize": null,
        "iexLastUpdated": null,
        "delayedPrice": null,
        "delayedPriceTime": null,
        "oddLotDelayedPrice": null,
        "oddLotDelayedPriceTime": null,
        "extendedPrice": null,
        "extendedChange": null,
        "extendedChangePercent": null,
        "extendedPriceTime": null,
        "previousClose": 190.41,
        "previousVolume": 1862266,
        "change": 1.02,
        "changePercent": 0.00536,
        "volume": null,
        "iexMarketPercent": null,
        "iexVolume": null,
        "avgTotalVolume": 3297376,
        "iexBidPrice": null,
        "iexBidSize": null,
        "iexAskPrice": null,
        "iexAskSize": null,
        "iexOpen": 191.43,
        "iexOpenTime": 1613163594232,
        "iexClose": 191.42,
        "iexCloseTime": 1613163595017,
        "marketCap": 95863002382,
        "peRatio": 27.66,
        "week52High": 199.96,
        "week52Low": 88.89,
        "ytdChange": 0.08976491701127284,
        "lastTradeTime": 1613163598250,
        "isUSMarketOpen": false
      }
    },
    "SNAP": {
      "quote": {
        "symbol": "SNAP",
        "companyName": "Snap Inc - Class A",
        "primaryExchange": "NEW YORK STOCK EXCHANGE, INC.",
        "calculationPrice": "close",
        "open": null,
        "openTime": null,
        "openSource": "official",
        "close": null,
        "closeTime": null,
        "closeSource": "official",
        "high": null,
        "highTime": 1613163593488,
        "highSource": "15 minute delayed price",
        "low": null,
        "lowTime": 1613140267381,
        "lowSource": "15 minute delayed price",
        "latestPrice": 61.97,
        "latestSource": "Close",
        "latestTime": "February 12, 2021",
        "latestUpdate": 1613174400003,
        "latestVolume": null,
        "iexRealtimePrice": null,
        "iexRealtimeSize": null,
        "iexLastUpdated": null,
        "delayedPrice": null,
        "delayedPriceTime": null,
        "oddLotDelayedPrice": null,
        "oddLotDelayedPriceTime": null,
        "extendedPrice": null,
        "extendedChange": null,
        "extendedChangePercent": null,
        "extendedPriceTime": null,
        "previousClose": 62.23,
        "previousVolume": 16315103,
        "change": -0.26,
        "changePercent": -0.00418,
        "volume": null,
        "iexMarketPercent": null,
        "iexVolume": null,
        "avgTotalVolume": 22609769,
        "iexBidPrice": null,
        "iexBidSize": null,
        "iexAskPrice": null,
        "iexAskSize": null,
        "iexOpen": 61.98,
        "iexOpenTime": 1613163597537,
        "iexClose": 61.98,
        "iexCloseTime": 1613163597537,
        "marketCap": 92334475055,
        "peRatio": -95.47,
        "week52High": 65.42,
        "week52Low": 7.89,
        "ytdChange": 0.23348726582784093,
        "lastTradeTime": 1613163597537,
        "isUSMarketOpen": false
      }
    },
    "LUMI": {
      "quote": {
        "symbol": "LUMI",
        "companyName": "",
        "primaryExchange": "",
        "calculationPrice": "previousclose",
        "open": null,
        "openTime": null,
        "openSource": "official",
        "close": null,
        "closeTime": null,
        "closeSource": "official",
        "high": null,
        "highTime": null,
        "highSource": null,
        "low": null,
        "lowTime": null,
        "lowSource": null,
        "latestPrice": 0.14,
        "latestSource": "Previous close",
        "latestTime": "May 9, 2003",
        "latestUpdate": 1052452800000,
        "latestVolume": null,
        "iexRealtimePrice": null,
        "iexRealtimeSize": null,
        "iexLastUpdated": null,
        "delayedPrice": null,
        "delayedPriceTime": null,
        "oddLotDelayedPrice": null,
        "oddLotDelayedPriceTime": null,
        "extendedPrice": null,
        "extendedChange": null,
        "extendedChangePercent": null,
        "extendedPriceTime": null,
        "previousClose": 0.14,
        "previousVolume": null,
        "change": 0,
        "changePercent": 0,
        "volume": null,
        "iexMarketPercent": null,
        "iexVolume": null,
        "avgTotalVolume": null,
        "iexBidPrice": null,
        "iexBidSize": null,
        "iexAskPrice": null,
        "iexAskSize": null,
        "iexOpen": null,
        "iexOpenTime": null,
        "iexClose": null,
        "iexCloseTime": null,
        "marketCap": 0,
        "peRatio": null,
        "week52High": 0,
        "week52Low": 0,
        "ytdChange": 0,
        "lastTradeTime": null,
        "isUSMarketOpen": false
      }
    },
    "GOOGL": {
      "quote": {
        "symbol": "GOOGL",
        "companyName": "Alphabet Inc - Class A",
        "primaryExchange": "NASDAQ/NGS (GLOBAL SELECT MARKET)",
        "calculationPrice": "close",
        "open": null,
        "openTime": null,
        "openSource": "official",
        "close": null,
        "closeTime": null,
        "closeSource": "official",
        "high": null,
        "highTime": null,
        "highSource": null,
        "low": null,
        "lowTime": null,
        "lowSource": null,
        "latestPrice": 2095.03,
        "latestSource": "Close",
        "latestTime": "February 12, 2021",
        "latestUpdate": 1613163682663,
        "latestVolume": null,
        "iexRealtimePrice": null,
        "iexRealtimeSize": null,
        "iexLastUpdated": null,
        "delayedPrice": null,
        "delayedPriceTime": null,
        "oddLotDelayedPrice": null,
        "oddLotDelayedPriceTime": null,
        "extendedPrice": null,
        "extendedChange": null,
        "extendedChangePercent": null,
        "extendedPriceTime": null,
        "previousClose": 2088.75,
        "previousVolume": 1024029,
        "change": 6.28,
        "changePercent": 0.00301,
        "volume": null,
        "iexMarketPercent": null,
        "iexVolume": null,
        "avgTotalVolume": 2262640,
        "iexBidPrice": null,
        "iexBidSize": null,
        "iexAskPrice": null,
        "iexAskSize": null,
        "iexOpen": 2096.19,
        "iexOpenTime": 1613163597047,
        "iexClose": 2096.19,
        "iexCloseTime": 1613163597047,
        "marketCap": 1420634069643,
        "peRatio": 35.75,
        "week52High": 2115,
        "week52Low": 1008.87,
        "ytdChange": 0.19836671900675557,
        "lastTradeTime": 1613163597047,
        "isUSMarketOpen": false
      }
    },
    "MSFT": {
      "quote": {
        "symbol": "MSFT",
        "companyName": "Microsoft Corporation",
        "primaryExchange": "NASDAQ/NGS (GLOBAL SELECT MARKET)",
        "calculationPrice": "close",
        "open": null,
        "openTime": null,
        "openSource": "official",
        "close": null,
        "closeTime": null,
        "closeSource": "official",
        "high": null,
        "highTime": null,
        "highSource": null,
        "low": null,
        "lowTime": null,
        "lowSource": null,
        "latestPrice": 244.99,
        "latestSource": "Close",
        "latestTime": "February 12, 2021",
        "latestUpdate": 1613163600739,
        "latestVolume": null,
        "iexRealtimePrice": null,
        "iexRealtimeSize": null,
        "iexLastUpdated": null,
        "delayedPrice": null,
        "delayedPriceTime": null,
        "oddLotDelayedPrice": null,
        "oddLotDelayedPriceTime": null,
        "extendedPrice": null,
        "extendedChange": null,
        "extendedChangePercent": null,
        "extendedPriceTime": null,
        "previousClose": 244.49,
        "previousVolume": 15751059,
        "change": 0.5,
        "changePercent": 0.00205,
        "volume": null,
        "iexMarketPercent": null,
        "iexVolume": null,
        "avgTotalVolume": 31736957,
        "iexBidPrice": null,
        "iexBidSize": null,
        "iexAskPrice": null,
        "iexAskSize": null,
        "iexOpen": 244.97,
        "iexOpenTime": 1613163599442,
        "iexClose": 244.97,
        "iexCloseTime": 1613163599442,
        "marketCap": 1847767440757,
        "peRatio": 36.51,
        "week52High": 245.92,
        "week52Low": 131.49,
        "ytdChange": 0.10352468752810007,
        "lastTradeTime": 1613163599442,
        "isUSMarketOpen": false
      }
    },
    "AMZN": {
      "quote": {
        "symbol": "AMZN",
        "companyName": "Amazon.com Inc.",
        "primaryExchange": "NASDAQ/NGS (GLOBAL SELECT MARKET)",
        "calculationPrice": "close",
        "open": null,
        "openTime": null,
        "openSource": "official",
        "close": null,
        "closeTime": null,
        "closeSource": "official",
        "high": null,
        "highTime": null,
        "highSource": null,
        "low": null,
        "lowTime": null,
        "lowSource": null,
        "latestPrice": 3277.71,
        "latestSource": "Close",
        "latestTime": "February 12, 2021",
        "latestUpdate": 1613166446555,
        "latestVolume": null,
        "iexRealtimePrice": null,
        "iexRealtimeSize": null,
        "iexLastUpdated": null,
        "delayedPrice": null,
        "delayedPriceTime": null,
        "oddLotDelayedPrice": null,
        "oddLotDelayedPriceTime": null,
        "extendedPrice": null,
        "extendedChange": null,
        "extendedChangePercent": null,
        "extendedPriceTime": null,
        "previousClose": 3262.13,
        "previousVolume": 2301417,
        "change": 15.58,
        "changePercent": 0.00478,
        "volume": null,
        "iexMarketPercent": null,
        "iexVolume": null,
        "avgTotalVolume": 3898853,
        "iexBidPrice": null,
        "iexBidSize": null,
        "iexAskPrice": null,
        "iexAskSize": null,
        "iexOpen": 3278.89,
        "iexOpenTime": 1613163595004,
        "iexClose": 3279.5,
        "iexCloseTime": 1613163598020,
        "marketCap": 1650539193779,
        "peRatio": 78.36,
        "week52High": 3552.25,
        "week52Low": 1626.03,
        "ytdChange": 0.011160241515783424,
        "lastTradeTime": 1613163598020,
        "isUSMarketOpen": false
      }
    }
  }